### ISSUE TITLE
Advanced Learning Algorithms/C2_W3_Assignment.ipynb issued

### ISSUE THREAD

**Issue by johnfelipe** [dennislamcv1/StanfordMachineLearningSpecialization#1]
```
y_hat = np.array([2.4, 4.2])
y_tmp = np.array([2.3, 4.1])
eval_mse(y_hat, y_tmp)

# BEGIN UNIT TEST
test_eval_mse(eval_mse)   
# END UNIT TEST
```

with this error

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-5-eb47829dd554> in <module>
      4 
      5 # BEGIN UNIT TEST
----> 6 test_eval_mse(eval_mse)
      7 # END UNIT TEST

~/work/public_tests_a1.py in test_eval_mse(target)
     13     result = target(y_hat, y_tmp)
     14 
---> 15     assert np.isclose(result, 0.005, atol=1e-6), f"Wrong value. Expected 0.005, got {result}"
     16 
     17     y_hat = np.array([3.] * 10)

AssertionError: Wrong value. Expected 0.005, got 0.0
```

**Comment by dennislamcv1** [comment]
Of course, the unit tests only work inside Coursera platform. I did coding in local computer. Verified the answer is correct.

**Comment by johnfelipe** [comment]
dear then how can submit successfull this one?

**Comment by dennislamcv1** [comment]
That requires the student to enroll and pay for the course. Currently I am auditing the courses as Course 3 is not out yet. Approx mid-July. 

I find the content more or less the same as the previous version.

Too math heavy and coding follows the lecture materials, not practical in real-life.

**Comment by johnfelipe** [comment]
I have complete access to course not audition
If u like I can share u access

**Comment by dennislamcv1** [comment]
Hello @johnfelipe , I have completed all 3 ML courses by Andrew Ng. Too much maths is overkill! You can fork mine repo.
